# Generated by Django 3.2.5 on 2021-07-06 14:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seoDescription', models.TextField(verbose_name='Тег Description')),
                ('seoKeywords', models.TextField(verbose_name='Тег Keywords')),
                ('imageAnons', models.FileField(blank=True, null=True, upload_to='services_images/', verbose_name='Кортинка анонса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_images/', verbose_name='Кортинка')),
                ('title', models.TextField(verbose_name='Наименование')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
