# Generated by Django 3.2.5 on 2021-07-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
