# Generated by Django 3.2.5 on 2021-07-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0004_rename_date_news_newsdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
